name: Build Aseprite extension
on: [ push ]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build extension
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '../elin-devtools.aseprite-extension'
          directory: 'src'

      - name: Archive extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: elin-devtools_build
          path: elin-devtools.aseprite-extension
