name: Create release bundle
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build extension
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '../elin-devtools.aseprite-extension'
          directory: 'src'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            ref
            elin-devtools.aseprite-extension
