name: Create release bundle
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: mkdir ./build

      - name: Build extension
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '../build/elin-devtools.aseprite-extension'
          directory: 'src'

      - run: cp -r ./ref ./build

      - name: Bundle release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '../aseprite-elin-devtools.zip'
          directory: 'build'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: aseprite-elin-devtools.zip
